config/routes.rb
Rails.application.routes.draw do
  get 'atacado_pedidos/index'
  get 'clientes/index'
  get 'lista_vendas/:venda_produto_id/index', to: 'lista_vendas#index', as: 'lista_vendas'
  get 'sat/index', to: 'sat#index'
  get 'clientes/get_cliente', to: 'clientes#get_cliente'
  get 'produtos/get_dataProduto', to: 'produtos#get_dataProduto'

  post 'lista_vendas/:venda_produto_id/set_retirada_quantidade', to: 'lista_vendas#set_retirada_quantidade', as: 'set_retira_quantidade_post'
  post 'lista_vendas/:venda_produto_id/get_desconto', to: 'lista_vendas#get_desconto', as: 'get_desconto'
  post 'lista_vendas/:venda_produto_id/set_cancela', to: 'lista_vendas#set_cancela', as: 'set_cancela'

  resources :venda_produtos do
    post :set_venda, on: :collection
    post :get_barcode, on: :collection
    get :get_barcode, on: :collection
    get :lista_vendas, on: :collection
  end
  resources :clientes
  resources :produtos
  resources :fornecedors
  resources :estoques
  resources :atacado_pedidos do
    post :set_venda, on: :collection
  end
  resources :users, only: [:new, :edit, :update, :create]

  get '/logs/:produto_id/index', to: 'logs#index', as: 'logs'
  get '/users/new', to: 'users#new'
  get '/search_estoque', to: 'estoques#search_estoque'
  get '/search_produto', to: 'produtos#search_produto'
  get '/search_fornecedor', to: 'fornecedors#search_fornecedor'
  get 'produtos/:id/subtrai', to: 'produtos#subtrai', as: 'subtrai'

  get 'welcome/index'
  get 'welcome/edit'
  get 'welcome/new'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root  to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atacado_pedido.rb
class AtacadoPedido < ApplicationRecord
  belongs_to :cliente
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/estoque.rb
class Estoque < ApplicationRecord
  include PgSearch::Model
  belongs_to :fornecedor
  belongs_to :produto

  pg_search_scope :search_produto, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
  include PgSearch::Model
  has_many :estoques

  pg_search_scope :search_fornecedor, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/lista_venda.rb
class ListaVenda < ApplicationRecord
  belongs_to :venda_produto
  has_many :produtos
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  include PgSearch::Model
  has_many :estoques

  pg_search_scope :search_produto, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/venda_produto.rb
class VendaProduto < ApplicationRecord
  has_many :produto
end

app/controllers/clientes_controller.rb
class ClientesController < DefaultController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  def get_cliente
    @cliente = Cliente.where(:id => params[:selected])
    render json: {data: @cliente}
  end
  def index
    @cliente = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to clientes_url(@cliente), notice: "Fornecedor was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to clientes_url(@cliente), notice: "Fornecedor was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy!

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Fornecedor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cliente_params
    params.require(:cliente).permit(:nome, :desc, :cnpj, :tel, :endereco, :cep, :email, :uf, :cidade)
  end
end

app/controllers/logs_controller.rb
class LogsController < WelcomeController
  def index
    @logs = Log.where(:produto_id => log_params)
  end

  private
  def log_params
    params.require(:produto_id)
  end
end

app/controllers/sat_controller.rb
class SatController < DefaultController
  extend FFI::Library, Prototype::_Prototype
  require_relative 'lib_ruby/biblioteca_sat'
  require_relative 'lib_ruby/sat_info_constantes'
  require 'ffi'

  ffi_lib FFI::Library::LIBC
  def index
    Biblioteca_sat.init('C:/SAT/SAT.dll')
  end
  private


end

app/controllers/users_controller.rb
class UsersController < DefaultController
  before_action :set_user, only: [:edit, :update]


  def index
    @user = User.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)

    if @user.save
      redirect_to welcome_index_path, notice: "Usuário cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(params_user)
        redirect_to welcome_index_path
      else
        render :edit
      end
  end

  private

  def params_user
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/lista_vendas_helper.rb
module ListaVendasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sat_helper.rb
module SatHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <td id="nome"><%= cliente.nome %></td>
  <td id="desc"><%= cliente.desc %></td>
  <td id="cnpj"><%= cliente.cnpj %></td>
  <td id="tel"><%= cliente.tel %></td>
  <td id="endereco"><%= cliente.endereco %></td>
  <td id="uf"><%= cliente.uf %></td>
  <td id="cep"><%= cliente.cep %></td>
  <td id="email"><%= cliente.email %></td>
</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label 'Nome/Razão Social', style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label 'Descrição (Opicional)', style: "display: block" %>
    <%= form.text_field :desc %>
  </div>

  <div>
    <%= form.label 'CPF/CNPJ', style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.label 'Telefone (Opicional)', style: "display: block" %>
    <%= form.text_field :tel %>
  </div>

  <div>
    <%= form.label 'Endereço', style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.label 'CEP', style: "display: block" %>
    <%= form.text_field :cep %>
  </div>

  <div>
    <%= form.label 'Email', style: "display: block" %>
    <%= form.email_field :email %>
  </div>

  <br>

  <div class="row">
    <div class="col-md-6">
      <%= form.label 'Estado: ' %>
      <%= form.select 'uf', '', {include_blank: 'Selecione...', display: 'disabled'}, id: 'selectEstado' %>
    </div>

    <div class="col-md-6">
      <%= form.label 'Cidade: ' %>
      <%= form.select 'cidade', '', {}, id: 'selectCidade' %>
    </div>
  </div>

  <br>

  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<div class="container-fluid">
  <%= render "form", cliente: @cliente %>

  <br>

  <div>
    <%= button_to "Mostrar", @cliente, class: 'btn btn-outline-info', method: :get %> |
    <%= button_to "Voltar", clientes_path, class: 'btn btn-outline-dark', method: :get %>
  </div>
</div>

<%= javascript_include_tag 'get_cidade' %>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div class="table-responsive">
  <table class="text-center table table-striped table-bordered table-hover" id="tabelaCliente">
    <thead>
    <tr>
      <th class="text-center">Nome/Razão Social</th>
      <th class="text-center">Descrição</th>
      <th class="text-center">CPF/CNPJ</th>
      <th class="text-center">Telefone</th>
      <th class="text-center">Endereço</th>
      <th class="text-center">UF</th>
      <th class="text-center">CEP</th>
      <th class="text-center">Email</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @cliente.each do |cliente| %>

      <tr>
        <%= render cliente %>

        <td id="botao_editar">
          <%= button_to "Editar", edit_cliente_path(cliente), class: 'btn btn-outline-info', method: :get%>
        </td>
        <td id="botao_mostrar"><%= button_to "Mostrar", cliente, class: 'btn btn-outline-info', method: :get %></td>
      </tr>

    <% end %>
    </tbody>
  </table>
</div>

<%= button_to "Novo cliente", new_cliente_path, class: 'btn btn-outline-success', method: :get %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<div class="container-fluid">
  <%= render "form", cliente: @cliente %>

  <br>

  <div>
    <%= button_to "Voltar", clientes_path, class: 'btn btn-outline-dark', method: :get %>
  </div>
</div>

<%= javascript_include_tag 'get_cidade' %>

app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div class="table-responsive">
  <table class="text-center table table-striped table-bordered table-hover" id="tabelaCliente">
    <thead>
    <tr>
      <th class="text-center">Nome/Razão Social</th>
      <th class="text-center">Descrição</th>
      <th class="text-center">CPF/CNPJ</th>
      <th class="text-center">Telefone</th>
      <th class="text-center">Endereço</th>
      <th class="text-center">UF</th>
      <th class="text-center">CEP</th>
      <th class="text-center">Email</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
      <tr>
        <%= render @cliente %>
    </tbody>
  </table>
</div>

<div>
  <%= button_to "Novo cliente", new_cliente_path, class: 'btn btn-outline-success', method: :get %> |
  <%= button_to "Editar", edit_cliente_path(@cliente), class: 'btn btn-outline-info', method: :get %> |
  <%= button_to "Voltar", clientes_path, class: 'btn btn-outline-dark', method: :get %>
</div>

<br>

<div class="d-flex flex-row justify-content-end mt-auto">
  <%= button_to "Deletar este cliente (não recomendado)", @estoque, class: 'btn btn-danger', method: :delete %>
</div>