config/routes.rb
Rails.application.routes.draw do
  get 'atacado_pedidos/index'
  get 'clientes/index'
  get 'lista_vendas/:venda_produto_id/index', to: 'lista_vendas#index', as: 'lista_vendas'
  get 'sat/index', to: 'sat#index'
  get 'clientes/get_cliente', to: 'clientes#get_cliente'
  get 'produtos/get_dataProduto', to: 'produtos#get_dataProduto'

  post 'lista_vendas/:venda_produto_id/set_retirada_quantidade', to: 'lista_vendas#set_retirada_quantidade', as: 'set_retira_quantidade_post'
  post 'lista_vendas/:venda_produto_id/get_desconto', to: 'lista_vendas#get_desconto', as: 'get_desconto'
  post 'lista_vendas/:venda_produto_id/set_cancela', to: 'lista_vendas#set_cancela', as: 'set_cancela'

  resources :venda_produtos do
    post :set_venda, on: :collection
    post :get_barcode, on: :collection
    get :get_barcode, on: :collection
    get :lista_vendas, on: :collection
  end
  resources :clientes
  resources :produtos
  resources :fornecedors
  resources :estoques
  resources :atacado_pedidos do
    post :set_venda, on: :collection
  end
  resources :users, only: [:new, :edit, :update, :create]

  get '/logs/:produto_id/index', to: 'logs#index', as: 'logs'
  get '/users/new', to: 'users#new'
  get '/search_estoque', to: 'estoques#search_estoque'
  get '/search_produto', to: 'produtos#search_produto'
  get '/search_fornecedor', to: 'fornecedors#search_fornecedor'
  get 'produtos/:id/subtrai', to: 'produtos#subtrai', as: 'subtrai'

  get 'welcome/index'
  get 'welcome/edit'
  get 'welcome/new'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root  to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atacado_pedido.rb
class AtacadoPedido < ApplicationRecord
  belongs_to :cliente
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/estoque.rb
class Estoque < ApplicationRecord
  include PgSearch::Model
  belongs_to :fornecedor
  belongs_to :produto

  pg_search_scope :search_produto, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
  include PgSearch::Model
  has_many :estoques

  pg_search_scope :search_fornecedor, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/lista_venda.rb
class ListaVenda < ApplicationRecord
  belongs_to :venda_produto
  has_many :produtos
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  include PgSearch::Model
  has_many :estoques

  pg_search_scope :search_produto, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/venda_produto.rb
class VendaProduto < ApplicationRecord
  has_many :produto
end

app/controllers/logs_controller.rb
class LogsController < WelcomeController
  def index
    @logs = Log.where(:produto_id => log_params)
  end

  private
  def log_params
    params.require(:produto_id)
  end
end

app/controllers/sat_controller.rb
class SatController < DefaultController
  extend FFI::Library, Prototype::_Prototype
  require_relative 'lib_ruby/biblioteca_sat'
  require_relative 'lib_ruby/sat_info_constantes'
  require 'ffi'

  ffi_lib FFI::Library::LIBC
  def index
    Biblioteca_sat.init('C:/SAT/SAT.dll')
  end
  private


end

app/controllers/welcome_controller.rb
class WelcomeController < DefaultController
  before_action :authenticate_user!
  def index
    @user = User.all
    @produtos = Produto.all
    @estoque = Estoque.all
    @logs = Log.all
    @vendas_produtos = VendaProduto.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/lista_vendas_helper.rb
module ListaVendasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sat_helper.rb
module SatHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
  <% if current_user.admin %>
      <h1>Produtos</h1>

      <div class="table-responsive">
        <table class="text-center table table-striped table-bordered table-hover" id="tabelaProdutoindexAdmin">
          <thead>
          <tr>
            <th class="text-center">Produto</th>
            <th class="text-center">Entrada</th>
            <th class="text-center">Quantidade Disponível</th>
            <th class="text-center">Retirada (Últimos 30 dias)</th>
            <th></th>
            <th></th>
          </tr>
          </thead>

          <tbody>
          <tr>
            <% @produtos.each do |showestoque| %>

              <td id="produtos"><%= showestoque.nome %></td>
              <td id="entrada">
                <% quantidade_total = @estoque.where(:produto_id => showestoque.id).where('status != ? and status != ?', 'Cancelado', 'Descartado') %>
                <%= t('valores.peso', value: '%0.3f' %quantidade_total.sum(:quantidade)) %>
              </td>
              <td id="quantidade"><%= t('valores.peso', value: '%0.3f' %showestoque.quantidade) %></td>
                <% verifica_data = @logs.where('data_retirada > ? and produto_id = ?', Date.today.days_ago(30), showestoque.id) %>
                <% soma = verifica_data.sum(:retirada) %>
                <td id="retirada"><%= link_to t('valores.peso', value: '%0.3f' %soma),  logs_path(showestoque.id) %></td>

              <td id="botao_mostrar"><%= button_to "Editar", edit_produto_path(showestoque), class: 'btn btn-outline-info', method: :get %></td>
              <td id="botao_retirar"><%= button_to 'Retirar', subtrai_path(showestoque), class: 'btn btn-outline-danger', method: :get %></td>
              </tr>

            <% end %>
            </tbody>
        </table>
      </div>
    <br>
    <br>
  <div class="table-responsive">
      <h1>Usuários</h1>
      <table class="text-center table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>E-mail</th>
          <th>Permissões</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @user.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.admin %></td>
            <td><%= button_to 'Editar', edit_user_path(user), class: 'btn btn-outline-info', method: :get %></td>
          </tr>

        <% end %>
        </tbody>
      </table>
      </div>
      <%= button_to 'Novo', new_user_path, class: 'btn btn-outline-success', method: :get %>
      <br>
    <br>

  <% else %>

<h1>Produtos</h1>

    <div class="table-responsive">
      <table class="text-center table table-striped table-bordered table-hover" id="tabelaProdutoindexUsuario">
        <thead>
        <tr>
          <th class="text-center">Produto</th>
          <th class="text-center">Quantidade Disponível</th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <tr>
          <% @produtos.each do |showestoque| %>

            <td id="produtos"><%= showestoque.nome %></td>
            <td id="quantidade"><%= t('valores.peso', value: '%0.3f' %showestoque.quantidade) %></td>
            <td id="botao_mostrar"><%= button_to "Editar", edit_produto_path(showestoque), class: 'btn btn-outline-info', method: :get %></td>
            <td id="botao_retirar"><%= button_to 'Retirar', subtrai_path(showestoque), class: 'btn btn-outline-danger', method: :get %></td>
            </tr>

          <% end %>
          </tbody>


          </table>
    </div>
<% end %>
    <%= button_to 'Sair', destroy_user_session_path, class: 'btn btn-outline-danger', method: :delete %>
    </div>