config/routes.rb
Rails.application.routes.draw do
  get 'atacado_pedidos/index'
  get 'clientes/index'
  get 'lista_vendas/:venda_produto_id/index', to: 'lista_vendas#index', as: 'lista_vendas'
  get 'sat/index', to: 'sat#index'
  get 'clientes/get_cliente', to: 'clientes#get_cliente'
  get 'produtos/get_dataProduto', to: 'produtos#get_dataProduto'

  post 'lista_vendas/:venda_produto_id/set_retirada_quantidade', to: 'lista_vendas#set_retirada_quantidade', as: 'set_retira_quantidade_post'
  post 'lista_vendas/:venda_produto_id/get_desconto', to: 'lista_vendas#get_desconto', as: 'get_desconto'
  post 'lista_vendas/:venda_produto_id/set_cancela', to: 'lista_vendas#set_cancela', as: 'set_cancela'

  resources :venda_produtos do
    post :set_venda, on: :collection
    post :get_barcode, on: :collection
    get :get_barcode, on: :collection
    get :lista_vendas, on: :collection
  end
  resources :clientes
  resources :produtos
  resources :fornecedors
  resources :estoques
  resources :atacado_pedidos do
    post :set_venda, on: :collection
  end
  resources :users, only: [:new, :edit, :update, :create]

  get '/logs/:produto_id/index', to: 'logs#index', as: 'logs'
  get '/users/new', to: 'users#new'
  get '/search_estoque', to: 'estoques#search_estoque'
  get '/search_produto', to: 'produtos#search_produto'
  get '/search_fornecedor', to: 'fornecedors#search_fornecedor'
  get 'produtos/:id/subtrai', to: 'produtos#subtrai', as: 'subtrai'

  get 'welcome/index'
  get 'welcome/edit'
  get 'welcome/new'

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root  to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/atacado_pedido.rb
class AtacadoPedido < ApplicationRecord
  belongs_to :cliente
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/estoque.rb
class Estoque < ApplicationRecord
  include PgSearch::Model
  belongs_to :fornecedor
  belongs_to :produto

  pg_search_scope :search_produto, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/fornecedor.rb
class Fornecedor < ApplicationRecord
  include PgSearch::Model
  has_many :estoques

  pg_search_scope :search_fornecedor, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/lista_venda.rb
class ListaVenda < ApplicationRecord
  belongs_to :venda_produto
  has_many :produtos
end

app/models/log.rb
class Log < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  include PgSearch::Model
  has_many :estoques

  pg_search_scope :search_produto, against: :nome, ignoring: :accents, using: { tsearch: { prefix: true } }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/venda_produto.rb
class VendaProduto < ApplicationRecord
  has_many :produto
end

app/controllers/logs_controller.rb
class LogsController < WelcomeController
  def index
    @logs = Log.where(:produto_id => log_params)
  end

  private
  def log_params
    params.require(:produto_id)
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < DefaultController
  before_action :set_produto, only: %i[ show edit update destroy ]
  before_action :sum_quantidade

  def get_dataProduto
    @produto = Produto.all

    render json: {data: @produto}
  end

  def search_produto
    if params[:search].blank?
      redirect_to estoques_path and return
    else
      @parameter = params[:search].downcase
      @produto = Produto.all
      @results = @produto.search_produto(@parameter)
    end
  end

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
    @estoque = Estoque.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
    @estoque = Estoque.all
    @usuario = current_user.admin
    if @usuario == false
      redirect_to welcome_index_path
    end
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
    @@subtrai = false
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    if @produto.quantidade == nil
      @produto.quantidade = 0
    end
    if @produto.retirada == nil
      @produto.retirada = 0
    end
    if @produto.preco == nil
      @produto.preco = 0
    end
    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    @produto_subtrai = Produto.find(params[:id])
    @verifica_retirada = Produto.where(:id => @produto_subtrai).pluck(:quantidade)
      if @produto.update(produto_params)
        if @@subtrai
            @retirada = (@produto.quantidade + @produto.retirada)

            if @verifica_retirada[0] < 0
              @subtracao = ( @produto_subtrai.quantidade + (-@produto.quantidade) )
            else
              @subtracao = ( @produto_subtrai.quantidade - @produto.quantidade )
            end
          Produto.where(:id => @produto_subtrai).update!(:quantidade => @subtracao, :retirada => @retirada)
          @usuario = current_user.email
          @log = Log.create!(:usuario => @usuario, :retirada => @produto.quantidade, :data_retirada => Date.today, :produto_id => @produto.id)

          redirect_to welcome_index_path
        else
          redirect_to produto_path(@produto)
        end
      end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def subtrai
    @produto_subtrai = Produto.find(params[:id])
    @@subtrai = true
  end

  private
    def sum_quantidade
      @quantidade = Estoque.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :desc, :quantidade, :codigo, :preco, :preco_unidade)
    end
end

app/controllers/sat_controller.rb
class SatController < DefaultController
  extend FFI::Library, Prototype::_Prototype
  require_relative 'lib_ruby/biblioteca_sat'
  require_relative 'lib_ruby/sat_info_constantes'
  require 'ffi'

  ffi_lib FFI::Library::LIBC
  def index
    Biblioteca_sat.init('C:/SAT/SAT.dll')
  end
  private


end

app/controllers/users_controller.rb
class UsersController < DefaultController
  before_action :set_user, only: [:edit, :update]


  def index
    @user = User.all
  end


  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)

    if @user.save
      redirect_to welcome_index_path, notice: "Usuário cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(params_user)
        redirect_to welcome_index_path
      else
        render :edit
      end
  end

  private

  def params_user
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/default_helper.rb
module DefaultHelper
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/helpers/lista_vendas_helper.rb
module ListaVendasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sat_helper.rb
module SatHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <% if current_user.admin %>
  <div class="col-md-4">
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= form.label 'Código', style: "display: block" %>
    <%= form.text_field :codigo, class: 'form-control' %>
  </div>

  <div class="col-md-4">
    <%= form.label 'Descrição', style: "display: block" %>
    <%= form.text_field :desc, class: 'form-control' %>
  </div>

    <div class="col-md-4">
      <%= form.label 'Preço (KG ou UNIDADE)', style: "display: block" %>
      <%= form.text_field :preco, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= form.label 'Ativar preço por Unidade', style: "display: block" %>
      <%= form.radio_button :preco_unidade, 'true' %> Sim <br>
      <%= form.radio_button :preco_unidade, 'false', checked: true %> Não
    </div>


<% end %>

  <div class="col-md-4">
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.text_field :quantidade, class: 'form-control' %>
  </div>

  <br>

  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/produtos/_form_subtrai.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col-md-4">
      <%= form.label :nome, style: "display: block" %>
      <%= form.label produto.nome, style: "display: block" %>
    </div>

    <div class="col-md-4">
      <%= form.label 'Descrição', style: "display: block" %>
      <%= form.label produto.desc, style: "display: block" %>
    </div>

  <div class="col-md-4">
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.text_field :quantidade, class: 'form-control', value: '' %>
  </div>

  <br>

  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/produtos/_formedit.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin %>
    <div class="col-md-4">
      <%= form.label :nome, style: "display: block" %>
      <%= form.text_field :nome, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= form.label 'Código', style: "display: block" %>
      <%= form.text_field :codigo, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= form.label 'Descrição', style: "display: block" %>
      <%= form.text_field :desc, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= form.label 'Preço por KG', style: "display: block" %>
      <%= form.text_field :preco, class: 'form-control' %>
    </div>

    <div class="col-md-4">
      <%= form.label 'Ativar preço por Unidade', style: "display: block" %>
      <% if produto.preco_unidade.nil? %>
        <%= form.radio_button :preco_unidade, 'true' %> Sim <br>
        <%= form.radio_button :preco_unidade, 'false', checked: true %> Não
      <% else %>
        <%= form.radio_button :preco_unidade, 'true' %> Sim <br>
        <%= form.radio_button :preco_unidade, 'false' %> Não
      <% end %>
    </div>
  <% end %>

  <div class="col-md-4">
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.text_field :quantidade, class: 'form-control', value: '%0.3f' % produto.quantidade %>
  </div>

  <br>

  <div>
    <%= form.submit class: 'btn btn-outline-success' %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">

  <td id="nome">
    <%= produto.nome %>
  </td>

  <td id="codigo">
    <%= produto.codigo %>
  </td>
  <% if current_user.admin %>
    <td id="desc">
      <%= produto.desc %>
    </td>
  <% end %>
  <td id="preco">
    <% if produto.preco == nil %>
      <%= t('valores.moeda', value: '%0,2f' %0) %>
    <% else %>
       <%= t('valores.moeda', value: '%0.2f' %produto.preco) %>
    <% end %>
  </td>
  <td id="entrada">
    <% quantidade_total = @estoque.where(:produto_id => produto.id) %>
    <% @@sum = t('valores.peso', value: '%0.3f' %quantidade_total.sum(:quantidade)) %>
    <%= @@sum %>
  </td>
  <td id="quantidade">
    <% quantidade = t('valores.peso', value: '%0.3f' %produto.quantidade) %>
    <%= quantidade %>
  </td>
  <td id="preco_unidade">
    <% if produto.preco_unidade.nil? or not produto.preco_unidade %>
      Não
    <% else %>
      Sim
    <% end %>
  </td>

</div>

app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<div class="container-fluid">
<%= render "formedit", produto: @produto %>

<br>

<div>
  <% if current_user.admin %>
  <%= button_to "Mostrar", @produto, class: 'btn btn-outline-info', method: :get %> |
  <%= button_to "Voltar", produtos_path, class: 'btn btn-outline-dark', method: :get %>


  <% else %>
    <%= button_to "Voltar", welcome_index_path, class: 'btn btn-outline-dark', method: :get %>
  <% end %>
</div>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<div class="table-responsive">
<table class="text-center table table-striped table-bordered table-hover" id="tabelaProduto">
  <thead>
  <tr>
    <th class="text-center">Produto</th>
    <th class="text-center">Código</th>
    <th class="text-center">Descrição</th>
    <th class="text-center">Preço</th>
    <th class="text-center">Entrada</th>
    <th class="text-center">Quantidade Disponível</th>
    <th class="text-center">Preço/Unidade</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

      <tbody>
      <tr>
      <% @produtos.each do |produto| %>
          <%= render produto %>

          <td id="botao_editar">
            <%= button_to "Editar", edit_produto_path(produto), class: 'btn btn-outline-info', method: :get %>
          </td>
        <td id="botao_mostrar">
          <%= button_to "Mostrar", produto, class: 'btn btn-outline-dark', method: :get %>
        </td>
          </tr>

      <% end %>
        </tbody>
</table>

<%= button_to "Novo produto", new_produto_path, class: 'btn btn-outline-success', method: :get %>
</div>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>

<div class="container-fluid">
<%= render "form", produto: @produto %>

<br>

<div>
  <%= button_to "Voltar", produtos_path, class: 'btn btn-outline-dark', method: :get %>
</div>
</div>

app/views/produtos/search_produto.erb
<h3>Resultado</h3>

<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<div class="table-responsive">
  <%= form_tag search_produto_path, method: :get do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Nome", class: 'form-control' %>
      <div class="input-group-btn">
        <%= button_tag 'Pesquisar', class: 'btn btn-primary', :nome => nil %>
      </div>
    </div>
  <% end %>
  <table class="text-center table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th class="text-center">Produto</th>
      <th class="text-center">Descrição</th>
      <th>Quantidade Disponível</th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <tr>
      <% @results.each do |result| %>
        <td><%= result.nome %></td>
        <td><%= result.desc %></td>
        <td><%= result.quantidade %></td>

        <td>
          <%= button_to "Editar", edit_produto_path(result), class: 'btn btn-outline-info', method: :get%>
        </td>
        <td id="mostrar">
          <%= button_to "Mostrar", result, class: 'btn btn-outline-dark', method: :get %>
        </td>
        </tr>
        </tbody>
      <% end %>
      </table>

  <%= button_to "Novo produto", new_produto_path, class: 'btn btn-outline-success', method: :get %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container-fluid">
<table class="text-center table table-striped table-bordered table-responsive-lg table-hover">
  <thead>
  <% if current_user.admin %>
  <th class="text-center">Produto</th>
    <th class="text-center">Código</th>
    <th class="text-center">Descrição</th>
    <th class="text-center">Preço/KG</th>
    <th class="text-center">Entrada</th>
    <th class="text-center">Quantidade Disponível</th>
    <th class="text-center">Preço/Unidade</th>

  <% else %>
  <th class="text-center">Produto</th>
  <th class="text-center">Quantidade</th>
  <% end %>
  </thead>
  <tbody>
    <%= render @produto %>
  </tbody>
</table>
</div>
<br>

<div class="container-fluid">
  <% if current_user.admin %>
    <%= button_to "Novo produto", new_produto_path, class: 'btn btn-outline-success', method: :get %> |
    <%= button_to "Editar", edit_produto_path(@produto), class: 'btn btn-outline-info', method: :get %> |
    <%= button_to "Retirar", subtrai_path(@produto), class: 'btn btn-outline-danger', method: :get %> |
    <%= button_to "Voltar", produtos_path, class: 'btn btn-outline-dark', method: :get %>

  <% else %>
    <%= button_to "Voltar", welcome_index_path, class: 'btn btn-outline-info', method: :get %>
  <% end %>
</div>

<br>
<br>

<div class="d-flex flex-row justify-content-end mt-auto">
  <%= button_to "Excluir produto (casos graves)", @produto, class: 'btn btn-danger', method: :delete %>
</div>

app/views/produtos/subtrai.html.erb
<h1>Retirada de estoque</h1>

<div class="container-fluid">
<%= render "form_subtrai", produto: @produto_subtrai %>

<br>

<div>
  <% if current_user.admin %>
    <%= button_to "Mostrar", @produto, class: 'btn btn-outline-info', method: :get %> |
    <%= button_to "Voltar", produtos_path, class: 'btn btn-outline-dark', method: :get %>


  <% else %>
    <%= button_to "Voltar", welcome_index_path, class: 'btn btn-outline-dark', method: :get %>
  <% end %>
</div>
</div>